version: '3'

services:
  webserver:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./app:/app
    depends_on:
      - db
  php:
    image: "my-php"
    build: 
      context: ./
      dockerfile: Dockerfile.php
    volumes:
      - ./app:/app
    depends_on:
      - db
  db:
    image: mysql:latest
    restart: always
    volumes:
      - ./database:/var/lib/mysql    
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "my_local_db"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "admin"
    ports:
      - 3306:3306
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - 8084:80
    environment:
      PMA_HOST: "db"
      MYSQL_ROOT_PASSWORD: "root"

volumes:
  database: {}
